token and nft contracts and unit tests
0x00Duke/BetOnChain pull request #2
Opened 2023-03-28 20:19 UTC by writetoyan

2023-03-29 08:12 UTC, fernandoandreotti requested changes
There are many files here that we shouldnt commit (`artifacts/`, `cache/`, etc). Could you add a .gitignore like this please?
https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/.gitignore

2023-03-29 08:15 UTC, fernandoandreotti commented on backend/contracts/BetOnChain.sol
> +    function mintWarriorNft() external {
I agree there is a bit of duplication here. We could probably have one function to mint at any of the levels, provided some switch statement.

2023-03-29 08:19 UTC, fernandoandreotti commented on backend/contracts/BetOnChain.sol
> +contract BetOnChain is Ownable {
This is just a comment, we should do this on a separate ticket.
 
 
This is a good start, I think we can base it a lot more on the Lottery contract, with start/end times for bets, possibility of winner(s) to withdraw the available prizes. In addition it should be a contract factory, like in https://blog.logrocket.com/cloning-solidity-smart-contracts-factory-pattern/.

2023-03-31 16:00 UTC, 0abst approved these changes
I could run the tests, it works:

![image](https://user-images.githubusercontent.com/92883939/229171330-621edb1f-c91b-4bb0-b99e-23ec5bdcae95.png)

2023-03-31 16:21 UTC, 0abst commented
Then just before the merge Conflicting files in:

 backend/hardhat.config.ts
backend/package.json 

could be found. I trust that for  backend/hardhat.config.ts the solution in main is better:

 
![image](https://user-images.githubusercontent.com/92883939/229175753-6b88e6d5-0be5-4670-b6c7-e98f1a20a72d.png)

For backend/package.json the code of  "token and nft contracts and unit tests #2 " has been kept

![image](https://user-images.githubusercontent.com/92883939/229175985-e354e92a-3c62-4573-a339-e887263ea19f.png)

2023-03-31 16:22 UTC, merged